config/routes.rb
Newbies::Application.routes.draw do

  root to: "front#show"  
 
  resources :timecards

  resources :tasks

  resources :jobs

  resources :comments

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :password_resets, only: [:new, :edit, :create, :update]

  get "visitors/welcome"

  get "visitors/how_it_works"

  get "visitors/thank_you"

  get "visitors/help_wanted"

  match '/visitors' => "visitors#front"

  match '/join' => 'users#join'

  match '/hire' => 'jobs#new'

  match '/login' => 'sessions#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  match '/timecard' => 'timecards#new'

  match '/timecard/summary' => 'timecards#summary'

  match '/admin' => 'users#admin'

  match '/site' => "siteindex#show"

  match '/front' => "visitors#front"

  match '/sitemap1.xml.gz' => 'sitemaps#show'

  
end

app/models/timecard.rb
# == Schema Information
#
# Table name: timecards
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  task        :string(255)
#  description :text
#  hours       :float
#  date        :datetime
#  rate        :float
#  approved    :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  email       :string(255)
#

class Timecard < ActiveRecord::Base
  attr_accessible :approved, :date, :description, :hours, 
                  :name, :rate, :task, :email



end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  before_filter :partner_required
  
  def index # GET /timecards
    @timecards = Timecard.all
  end

  def show # GET /timecards/1
    @timecard = Timecard.find(params[:id])
  end

  def summary
    timecard_names = Timecard.all.collect(&:name).uniq
    @summation = []
    @total_net_hours = 0
    @total_hours = 0
    timecard_names.each do |n|
      hours = Timecard.where("name = ?", n).sum(:hours)

       cards = Timecard.where("name = ?", n)

        net = 0
        cards.each do |card|
          net += card.hours * card.rate
        end      
      @summation << [n, hours, net]
      @total_net_hours += net
      @total_hours += hours   
    end
  end 

  def new # GET /timecards/new
    @timecard = Timecard.new
  end

  def edit # GET /timecards/1/edit
    @timecard = Timecard.find(params[:id])
  end

  def create # POST /timecards
    @timecard = Timecard.new(params[:timecard])
    if @timecard.save
      AdminMailer.time_notice(@timecard).deliver
      AdminMailer.time_confirmation(@timecard).deliver
      redirect_to @timecard, notice: 'Timecard was successfully created.' 
    else
      render action: "new" 
    end
  end
  
  def update # PUT /timecards/1
    @timecard = Timecard.find(params[:id])    
    if @timecard.update_attributes(params[:timecard])
      redirect_to @timecard, notice: 'Timecard was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy # DELETE /timecards/1
    @timecard = Timecard.find(params[:id])
    @timecard.destroy
    redirect_to timecards_url 
  end
end

app/helpers/timecards_helper.rb
module TimecardsHelper
end

app/views/timecards/_form.html.erb
<%= form_for(@timecard) do |f| %>
  <% if @timecard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timecard.errors.count, "error") %> prohibited this timecard from being saved:</h2>

      <ul>
      <% @timecard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :value => current_user.email %>
  </div>
  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task, :size => 90 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => '90x10' %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label "Rate: A decimal multiplier between 0 and 1" %><br />
    <%= f.text_field :rate %>
  </div>

  <% if current_user.role == 'admin' %>
    <div class="field">
      <%= f.label :approved %><br />
      <%= f.check_box :approved %>
    </div>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
  <% else %>
    <%=f.hidden_field :approved, :value => :false %>
    <%=f.hidden_field :name, :value => current_user.name %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timecards/edit.html.erb
<h1>Editing timecard</h1>

<%= render 'form' %>

<%= link_to 'Show', @timecard %> |
<%= link_to 'Back', timecards_path %>

app/views/timecards/index.html.erb
<h1>All Timecards</h1>



<table class="table">
  <thead>
    <th>Date</th>
    <th>Name</th>
    <th>Net</th>
    <th>Hours</th>    
    <th>Rate</th>
    <th>Task</th>
    <th>Description</th>
    <% if current_user.role == 'admin' %>
        <th>Approved</th>
        <th>Email</th>
    <% end %>
  </thead>
<tbody>
    <% @timecards.each do |timecard| %>
    <% if timecard.hours.nil? then timecard.hours = 0 end %>
    <% if timecard.rate.nil? then timecard.rate = 0 end %>
      <tr>
        <td><%= timecard.date.to_s(:simple) %></td>
        <td><%= timecard.name %></td>
        <td><%= timecard.hours * timecard.rate %></td>
        <td><%= timecard.hours %></td>
        <td><%= timecard.rate %></td>
        <td>Task<span><%= timecard.task %></span></td>
        <td>Description<span><%= timecard.description %></span></td>
  
        <% if current_user.role == 'admin' %>
            <td><%= timecard.approved %></td>
            <td><%= timecard.email %></td>
            <td><%= link_to 'Show', timecard %></td>
            <td><%= link_to 'Edit', edit_timecard_path(timecard) %></td>
            <td><%= link_to 'Destroy', timecard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
</tbody>
</table>

<br />
<%= link_to 'Summary', "/timecard/summary" %> |
<%= link_to 'New Timecard', new_timecard_path %>

app/views/timecards/new.html.erb
<h1>New timecard entry</h1>

<%= render 'form' %>

<%= link_to 'Back', timecards_path %> | 
<%= link_to 'Show All', '/timecards' %>

app/views/timecards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @timecard.name %>
</p>

<p>
  <b>Task:</b>
  <%= @timecard.task %>
</p>

<p>
  <b>Description:</b>
  <%= @timecard.description %>
</p>

<p>
  <b>Hours:</b>
  <%= @timecard.hours %>
</p>

<p>
  <b>Date:</b>
  <%= @timecard.date %>
</p>

<% if current_user.role == 'admin' %>

  <p>
    <b>Rate:</b>
    <%= @timecard.rate %>
  </p>

  <p>
    <b>Approved:</b>
    <%= @timecard.approved %>
  </p>

<% end %>


<%= link_to 'Edit', edit_timecard_path(@timecard) %> |
<%= link_to 'Back', timecards_path %>

app/views/timecards/summary.html.erb
<h1>Time Summary</h1>

<table class="table">
  <thead>
    <th>Name</th>
    <th>Net Hours</th>
    <th>Total Hours</th>    
    <th>Per Cent</th>
  </thead>
<tbody>
  <tr>
    <td>Everybody</td>
    <td><%= @total_net_hours.round(2) %></td>
    <td><%= @total_hours.round(2) %></td>
    <td>100.0</td>
  </tr>

    <% @summation.each do |sum| %>
      <tr>
        <td><%= sum[0] %></td>
        <td><%= sum[2].round(2) %></td>
        <td><%= sum[1] %></td>
        <td><%= @total_net_hours>0 ? (sum[2]/@total_net_hours*100).round(2) : "error" %></td>
 
      </tr>
    <% end %>
</tbody>
</table>

<br />

<%= link_to 'New Timecard', new_timecard_path %> |
<%= link_to 'Show All', '/timecards' %>