config/routes.rb
Newbies::Application.routes.draw do

  root to: "front#show"  
 
  resources :timecards

  resources :tasks

  resources :jobs

  resources :comments

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :password_resets, only: [:new, :edit, :create, :update]

  get "visitors/welcome"

  get "visitors/how_it_works"

  get "visitors/thank_you"

  get "visitors/help_wanted"

  match '/visitors' => "visitors#front"

  match '/join' => 'users#join'

  match '/hire' => 'jobs#new'

  match '/login' => 'sessions#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  match '/timecard' => 'timecards#new'

  match '/timecard/summary' => 'timecards#summary'

  match '/admin' => 'users#admin'

  match '/site' => "siteindex#show"

  match '/front' => "visitors#front"

  match '/sitemap1.xml.gz' => 'sitemaps#show'

  
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                  :integer          not null, primary key
#  client_name         :string(255)
#  client_email        :string(255)
#  description         :text
#  initial_date        :datetime
#  task_list_complete  :datetime
#  proposal_date       :datetime
#  proposer            :string(255)
#  acceptance_date     :datetime
#  proposal_amount     :integer
#  responsible_partner :string(255)
#  master              :string(255)
#  status              :string(255)
#  percent_complete    :integer
#  member              :string(255)
#  completion_date     :datetime
#  contract_amount     :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  job_name            :string(255)
#  comments            :text
#  attachment          :string(255)
#  binary_attachment   :binary
#

class Job < ActiveRecord::Base
  attr_accessible :acceptance_date, :client_email, :client_name, 
                  :completion_date, :contract_amount, :description, 
                  :initial_date, :master, :member, :percent_complete, 
                  :proposal_amount, :proposal_date, :proposer, 
                  :responsible_partner, :status, :task_list_complete, 
                  :attachment, :binary_attachment, :attached_file
  attr_accessor :attached_file

 
  before_save do
    if attached_file
      self.binary_attachment = attached_file.read
      self.attachment = attached_file.original_filename
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_filter :login_required, only: [:new, :create]
  before_filter :partner_required, only: [:edit]

  
  def index # GET /jobs
    @jobs = Job.all
  end
 
  def show # GET /jobs/1
    @job = Job.find(params[:id])
  end
 
  def new # GET /jobs/new
    @job = Job.new
  end

  def edit # GET /jobs/1/edit
    @job = Job.find(params[:id])
  end

  def create # POST /jobs
    @job = Job.new(params[:job])
    if @job.save
      AdminMailer.job_notice(@job).deliver
      redirect_to @job, notice: 'Job was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update # PUT /jobs/1
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      redirect_to @job, notice: 'Job was successfully updated' 
    else
      render action: "edit" 
    end
  end
  
  def destroy # DELETE /jobs/1
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_url 
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => {:multipart => true} do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :client_name, :style => "width:380px;" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :client_email, :style => "width:380px;" %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 10, :style => "width:800px;" %>
  </div>
  <div>
    <%= f.label "Attachment (5MB limit)" %>
    <%= f.file_field :attached_file %>
  </div>


  <% if current_user %>
    <% if current_user.role == 'admin' || current_user.role == 'master' || current_user.role == 'partner'%>

      <div class="field">
        <%= f.label :initial_date %><br />
        <%= f.date_select :initial_date %>
      </div>
      <div class="field">
        <%= f.label :task_list_complete %><br />
        <%= f.date_select :task_list_complete %>
      </div>
      <div class="field">
        <%= f.label :proposal_date %><br />
        <%= f.date_select :proposal_date %>
      </div>
      <div class="field">
        <%= f.label :proposer %><br />
        <%= f.text_field :proposer %>
      </div>
      <div class="field">
        <%= f.label :acceptance_date %><br />
        <%= f.date_select :acceptance_date %>
      </div>
      <div class="field">
        <%= f.label :proposal_amount %><br />
        <%= f.number_field :proposal_amount %>
      </div>
      <div class="field">
        <%= f.label :responsible_partner %><br />
        <%= f.text_field :responsible_partner %>
      </div>
      <div class="field">
        <%= f.label :master %><br />
        <%= f.text_field :master %>
      </div>
      <div class="field">
        <%= f.label :status %><br />
        <%= f.text_field :status %>
      </div>
      <div class="field">
        <%= f.label :percent_complete %><br />
        <%= f.number_field :percent_complete %>
      </div>
      <div class="field">
        <%= f.label :member %><br />
        <%= f.text_field :member %>
      </div>
      <div class="field">
        <%= f.label :completion_date %><br />
        <%= f.date_select :completion_date %>
      </div>
      <div class="field">
        <%= f.label :contract_amount %><br />
        <%= f.number_field :contract_amount %>
      </div>
    <% end %>

  <% end %>

  <div class="actions">
    <%= f.submit "SEND" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>

    <th>Client Name&nbsp;&nbsp;&nbsp;</th>
    <th>Job Name&nbsp;&nbsp;&nbsp;</th>
    <th>Contract Amount&nbsp;&nbsp;&nbsp;</th>
    <th>Responsible Partner&nbsp;&nbsp;&nbsp;</th>
    <th>Percent Complete&nbsp;&nbsp;&nbsp;</th>
    <th>Completion Date&nbsp;&nbsp;&nbsp;</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.client_name %></td>
    <td><%= job.job_name %></td>
    <td><%= job.contract_amount %></td>
    <td><%= job.responsible_partner %></td>
    <td><%= job.percent_complete %></td>
    <td><%= job.completion_date %></td>

    <% if current_user then %>

        <% if current_user.role == 'admin' || current_user.role == 'master' || current_user.role == 'partner'%>    
            <td><%= link_to ' Show ', job %></td>
        <% end %>
        <% if current_user.role == 'admin' || current_user.role == 'partner'%>
            <td><%= link_to ' Edit ', edit_job_path(job) %></td>
        <% end %>
        <% if current_user.name == job.client_name %>
            <td><%= link_to ' Show ', job %></td>
        <% end %>

    <% end -%>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>How Can We Help?</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client name:</b>
  <%= @job.client_name %>
</p>

<p>
  <b>Client email:</b>
  <%= @job.client_email %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>

<p>
  <b>Initial date:</b>
  <%= @job.initial_date %>
</p>

<p>
  <b>Task list complete:</b>
  <%= @job.task_list_complete %>
</p>

<p>
  <b>Proposal date:</b>
  <%= @job.proposal_date %>
</p>

<p>
  <b>Proposer:</b>
  <%= @job.proposer %>
</p>

<p>
  <b>Acceptance date:</b>
  <%= @job.acceptance_date %>
</p>

<p>
  <b>Proposal amount:</b>
  <%= @job.proposal_amount %>
</p>

<p>
  <b>Responsible partner:</b>
  <%= @job.responsible_partner %>
</p>

<p>
  <b>Master:</b>
  <%= @job.master %>
</p>

<p>
  <b>Status:</b>
  <%= @job.status %>
</p>

<p>
  <b>Percent complete:</b>
  <%= @job.percent_complete %>
</p>

<p>
  <b>Member:</b>
  <%= @job.member %>
</p>

<p>
  <b>Completion date:</b>
  <%= @job.completion_date %>
</p>

<p>
  <b>Contract amount:</b>
  <%= @job.contract_amount %>
</p>

<% if @job.attachment %>

<p>
  <b>Attachment:</b>
  <%= @job.attachment %>
  <img alt="Product <%= @job.attachment -%>" title="<%= @job.attachment %>" src="data:image/png;base64, <%= Base64.encode64(@job.binary_attachment) -%>" />
</p>

<% end %>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>