config/routes.rb
Newbies::Application.routes.draw do

  root to: "front#show"  
 
  resources :timecards

  resources :tasks

  resources :jobs

  resources :comments

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :password_resets, only: [:new, :edit, :create, :update]

  get "visitors/welcome"

  get "visitors/how_it_works"

  get "visitors/thank_you"

  get "visitors/help_wanted"

  match '/visitors' => "visitors#front"

  match '/join' => 'users#join'

  match '/hire' => 'jobs#new'

  match '/login' => 'sessions#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  match '/timecard' => 'timecards#new'

  match '/timecard/summary' => 'timecards#summary'

  match '/admin' => 'users#admin'

  match '/site' => "siteindex#show"

  match '/front' => "visitors#front"

  match '/sitemap1.xml.gz' => 'sitemaps#show'

  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  approval               :boolean          default(FALSE)
#  password_digest        :string(255)
#  role                   :string(255)
#  mail                   :string(255)
#  telephone              :string(255)
#  comment                :text
#  auth_token             :string(255)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  PHP                    :integer
#  Ruby_on_rails          :integer
#  Javascript             :integer
#  HTML                   :integer
#  CSS                    :integer
#  Flash                  :integer
#  jquery                 :integer
#  MySQL                  :integer
#  Postgresql             :integer
#  GitHub                 :integer
#  WordPress              :integer
#  Graphics               :integer
#  Video                  :integer
#  Audio                  :integer
#  Adobe_photoshop        :integer
#  Gimp                   :integer
#  SEO                    :integer
#  SEM                    :integer
#

class User < ActiveRecord::Base
	has_secure_password
	before_create { generate_token(:auth_token) }
  before_save { |user| user.email = email.downcase }
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, length: { minimum: 6 }, :if => :should_validate_password?
	validates :password_confirmation, presence: true, :if => :should_validate_password?
  attr_accessor :update_password
  attr_protected

	def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!
	  AdminMailer.password_reset(self).deliver
	end

  def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end
	
	def should_validate_password?
		@update_password || new_record?
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_required, except: [:update_password, :join, :create, :new ]
  before_filter :admin_or_self, only: [:update_password]
  skip_before_filter :login_required, only: [ :join, :create, :new ]

  def join # GET /join
    @title = "Sign Up Form"
    @button_label = "Sign Me Up!"
    @user = User.new
    @update_password = true
    render "users/new"
  end

  def create   # POST /users

    @user = User.new(params[:user])
    if @user.save && !current_user
      AdminMailer.join_notice(@user).deliver
      redirect_to root_path, notice: "You have been listed as a new user. Your account will take some time to set up. An email will be sent to you when your registration is complete." 
    elsif @user.save 
      redirect_to @user, notice: "New user created: #{@user.name}"
    else
      render action: "new" 
    end
  end

  def new # GET /users/new
    @update_password = true
    @user = User.new
  end

  def edit # GET /users/1/edit
    @user = User.find(params[:id])
  end

  def index # GET /users
    @users = User.all
  end

  def show # GET /users/:id
    @user = User.find(params[:id])
  end

  def update # PUT /users/:id
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Your  information was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy # DELETE /users/:id
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p id="notice"><%= notice %></p>
<br>
<br>
<div class="row-fluid">
  <div class="span6 center">
    <div class = "leftside control-group">

      <div class="controls">
        <p><%= f.label "Name (required):" %>
        <%= f.text_field :name, 
            :value => (current_user ? current_user.name : "") %></p>
      </div>

      <div class="controls">
        <p><%= f.label "Email (required):" %>
        <%= f.text_field :email %></p>
      </div>
 
      <% if @update_password then %>
        <div class="controls">
          <p><%= f.label "Password (required):"%>
          <%= f.password_field :password %></p>    
        </div>
        <div class="controls">
          <p><%= f.label "Confirm Password" %>
          <%= f.password_field :password_confirmation %></p>    
        </div>
      <% end %>

    
 <% if current_user && current_user.role == 'admin' %>
         <div class="field">
          <%= f.label :role %><br />
          <%= f.text_field :role %>
        </div>
        <div class="field">
          <%= f.label :approval %><br />
          <%= f.check_box :approval %>
        </div>
      <% else %>
        <div>
          <p><%= @note %></p>
        </div>
        <%=f.hidden_field :approval, :value => :false %>
        <%=f.hidden_field :role, :value => 'member' %>
      <% end %>

      <div class="actions">
        <%= f.submit @button_label %>
      </div>
    </div>
  </div>

  <div class="span6 center">
    <h3>Tell Us About Your Skilz!</h3>
    <table class="table">
      
      <% [:PHP, :Ruby_on_rails, :Javascript, :HTML,:CSS, :Flash, 
          :jquery, :MySQL, :Postgresql, :GitHub, :WordPress, 
          :Graphics, :Video, :Audio, :Adobe_photoshop, 
          :Gimp, :SEO, :SEM].each do |skill| %>
      <tr>
      <td><%= f.label skill %></td>
      <td><%= f.radio_button skill, '0' %> NONE</td>
      <td><%= f.radio_button skill, '1' %> SOME</td>
      <td><%= f.radio_button skill, '2' %> LOTS</td>
      <td><%= f.radio_button skill, '3' %> TONS</td>
      </tr>
    
      <% end %>
    </table>
  </div>
</div>

<% end %>

app/views/users/admin.html.erb
<% if !current_user.role == 'admin' %>
  <% redirect_to "/public/500.html" %>
<% end %>
<h1>Admin</h1>
<p><%= current_user.name %></p>
<p><%= current_user.email %></p>
<div id="adminlinks">
  <ul class="nav">
    <li style="margin-left: 1px"><a href="/comments"><span>Comments</span></a></li>
    <li><a href="/users"><span>Users</span></a></li>
    <li><a href="/jobs"><span>Jobs</span></a></li>
    <li><a href="/tasks"><span>Tasks</span></a></li>
    <li><a href="/timecards"><span>Timecards</span></a></li>
    <li><a href="/sitemap/"><span>Show Sitemap</span></a></li>
  	<li><a href="/sitemap/send"><span>Send Sitemap</span></a></li>
  </ul>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table id="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
    <% if current_user.role == 'admin' %>
      <td>&nbsp;&nbsp;<%= link_to 'Show', user %>&nbsp;&nbsp;</td>
      <td><%= link_to 'Edit', edit_user_path(user), :id => 'edit' + user.id.to_s %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td><%= button_to "DELETE "+user.name, user, :method=>:delete, :class=>:destroy %></td>
    <% end %>
  </tr>
<% end %>
</table>
s
<br />

<%= 
link_to 'New User', new_user_path %>

<br />
<%= link_to 'Admin Page', admin_path %>

app/views/users/new.html.erb
<% provide(:title, 'Registration') %>
<h1>Register</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Role:</b>
  <%= @user.role %>
</p>

<p>
  <b>Approval:</b>
  <%= @user.role %>
</p>

<p>
  <b>ID:</b>
  <%= @user.role %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>